title: Project log
author: Amélie
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a place where you can find more info about me and my projects.

# social links
twitter_username: damn_lovecook # DO NOT include the @ character, or else the build will fail!
github_username:  aweligo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
